# -*- coding: utf-8 -*-
"""TicTacToe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUmSZ67hd7UKlKWNmzzvX22WHdrlCxvr
"""

import math
import RPi.GPIO as GPIO
import time

# ---------------- GPIO SETUP ----------------
UP = 5
DOWN = 6
LEFT = 13
RIGHT = 19
SELECT = 26

GPIO.setmode(GPIO.BCM)
GPIO.setup([UP, DOWN, LEFT, RIGHT, SELECT], GPIO.IN, pull_up_down=GPIO.PUD_UP)

# ---------------- GAME SETUP ----------------
board = [
    ["_", "_", "_"],
    ["_", "_", "_"],
    ["_", "_", "_"]
]

cursor = [0, 0]  # row, col

# ---------------- DISPLAY ----------------
def print_board():
    for i in range(3):
        row = ""
        for j in range(3):
            if [i, j] == cursor:
                row += f"[{board[i][j]}] "
            else:
                row += f" {board[i][j]}  "
        print(row)
    print("\n")

# ---------------- GAME LOGIC ----------------
def check_winner(b):
    for row in b:
        if row.count(row[0]) == 3 and row[0] != "_":
            return row[0]

    for c in range(3):
        if b[0][c] == b[1][c] == b[2][c] != "_":
            return b[0][c]

    if b[0][0] == b[1][1] == b[2][2] != "_":
        return b[0][0]

    if b[0][2] == b[1][1] == b[2][0] != "_":
        return b[0][2]

    return None

def get_empty(b):
    return [(i, j) for i in range(3) for j in range(3) if b[i][j] == "_"]

# ---------------- MINIMAX AI ----------------
def minimax(b, is_max):
    winner = check_winner(b)

    if winner == "O":
        return 1
    if winner == "X":
        return -1
    if not get_empty(b):
        return 0

    if is_max:
        best = -math.inf
        for i, j in get_empty(b):
            b[i][j] = "O"
            best = max(best, minimax(b, False))
            b[i][j] = "_"
        return best
    else:
        best = math.inf
        for i, j in get_empty(b):
            b[i][j] = "X"
            best = min(best, minimax(b, True))
            b[i][j] = "_"
        return best

def ai_move():
    best_score = -math.inf
    move = None

    for i, j in get_empty(board):
        board[i][j] = "O"
        score = minimax(board, False)
        board[i][j] = "_"

        if score > best_score:
            best_score = score
            move = (i, j)

    if move:
        board[move[0]][move[1]] = "O"

# ---------------- BUTTON HANDLING ----------------
def move_cursor():
    global cursor

    if GPIO.input(UP) == 0 and cursor[0] > 0:
        cursor[0] -= 1
        time.sleep(0.2)

    if GPIO.input(DOWN) == 0 and cursor[0] < 2:
        cursor[0] += 1
        time.sleep(0.2)

    if GPIO.input(LEFT) == 0 and cursor[1] > 0:
        cursor[1] -= 1
        time.sleep(0.2)

    if GPIO.input(RIGHT) == 0 and cursor[1] < 2:
        cursor[1] += 1
        time.sleep(0.2)

def select_move():
    if GPIO.input(SELECT) == 0:
        r, c = cursor
        if board[r][c] == "_":
            board[r][c] = "X"

            winner = check_winner(board)
            if not winner:
                ai_move()

            time.sleep(0.3)

# ---------------- MAIN LOOP ----------------
try:
    while True:
        print_board()
        move_cursor()
        select_move()

        winner = check_winner(board)
        if winner:
            print("Winner:", winner)
            break

        time.sleep(0.1)

except KeyboardInterrupt:
    GPIO.cleanup()